---
- name: Allow loopback address
  ansible.builtin.iptables:
    chain: INPUT
    in_interface: lo
    jump: ACCEPT
    comment: Allow loopback address

- name: Allow established and related
  ansible.builtin.iptables:
    chain: INPUT
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT
    comment: Allow established and related

- name: Allow ssh
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_port: '22'
    jump: ACCEPT
    comment: Allow ssh 22

- name: Set INPUT policy to DROP
  ansible.builtin.iptables:
    chain: INPUT
    policy: DROP
    comment: Drop policy for INPUT chain
