---
- name: Create group
  group:
    name: {{ user_name }}
    gid: '1001'
    state: present

- name: Add user
  user:
    name: {{ user_name }}
    state: present
    uid: '1001'
    groups:
      - ansible
      - sudo
      - docker
      - kvm
      - lxd

- name: Create ssh folder
  file:
    path: /home/{{ user_name }}/.ssh
    owner: {{ user_name }}
    group: {{ user_name }}
    mode: "0700"
    state: directory

- name: Add authorized keys for user
  copy:
    src: roles/common/files/ssh_authorized_keys
    dest: /home/{{ user_name }}/.ssh/authorized_keys
    owner: {{ user_name }}
    group: {{ user_name }}
    mode: "0700"

- name: Check for user sudo access
  shell: grep -w -c "{{ user_name }}    ALL=(ALL:ALL) ALL" /etc/sudoers || true
  register: check_root

- name: Give passwd to user
  lineinfile:
    line: "{{ user_name }}    ALL=(ALL:ALL) ALL"
    dest: /etc/sudoers
    validate: visudo -cf %s
  when: check_root.stdout == "0"
