---
- name: Create group
  ansible.builtin.group:
    name: "{{ user_name }}"
    gid: '1001'
    state: present

- name: Add user
  ansible.builtin.user:
    name: "{{ user_name }}"
    state: present
    uid: '1001'
    shell: /bin/bash
    groups:
      - ansible
      - sudo
      - kvm
  ignore_errors: true

- name: Create ssh folder
  ansible.builtin.file:
    path: /home/{{ user_name }}/.ssh
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: "0700"
    state: directory

- name: Add authorized keys for user
  ansible.builtin.copy:
    src: ssh_authorized_keys
    dest: /home/{{ user_name }}/.ssh/authorized_keys
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: "0700"

- name: Check for user sudo access
  ansible.builtin.shell: grep -w -c "{{ user_name }}    ALL=(ALL:ALL) ALL" /etc/sudoers || true
  register: check_root

- name: Give passwd to user
  ansible.builtin.lineinfile:
    line: "{{ user_name }}    ALL=(ALL:ALL) ALL"
    dest: /etc/sudoers
    validate: visudo -cf %s
  when: check_root.stdout == "0"
